config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create, :new]
    end
  end
  resources :posts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter
  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def update_post_counter
    author.increment!(:post_counter)
  end

  def five_recent_comments
    comments.order(created_at: :desc).last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def last_three_posts
    posts.order(created_at: :desc).last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to user_post_path(current_user, @comment.post)
    else
      render :create
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def new
    @like = Like.new
  end

  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]
    if @like.save
      redirect_to user_post_path(current_user, @like.post)
    else
      render :create
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.includes([:author]).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      format.html do
        if @post.save
          redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
        else
          render :new
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :likes_counter, :comments_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    if params[:id] == 'null'
      redirect_to users_path
    else
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
# require "capybara/rspec"
module ApplicationHelper
end

app/helpers/comments_helper.rb
# require "capybara/rspec"
module CommentsHelper
end

app/helpers/likes_helper.rb
# require "capybara/rspec"
module LikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= render "shared/navbar" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<section>
 <h2>List of Posts</h2>
  <button type="button" class="btn btn-info mt-3 mb-5">
    <%= link_to "Create A Post", new_post_path(current_user.id) , class: "new-post-link" %>
  </button>
  <%= render 'shared/user', user:@user %>
  <ul>
    <% @posts.each do |post|%>
      <li>
        <a id="show-btn-<%=post.id%>" href=<%=user_post_path(:user_id => @user.id, :id => post.id)%>>
          <div class="post-cont">
            <%= render 'shared/post', {user: @user, post: post} %>
            <ul class="comments-cont">
              <% if post.comments_counter > 0%>
                <%post.five_recent_comments.each do |comment|%>
                <li><%= comment.text %></li>
                <%end%>
              <%else%>
                <li>No comment<li>
              <%end%>
            <ul>
          </div>
        </a>
      </li>
    <%end%>
  </ul>
  <div class="all-posts-btn">
    <a href="#"><button type="button">Pagination</button></a>
  </div>
</section>

app/views/posts/new.html.erb
<div class="post-form-cont">
  <h1>Create a Post </h1>
  <%= form_with model: @post, class:"post-form", method: :post do |form| %>
      <%= form.hidden_field :comments_counter, value:0 %>
      <%= form.hidden_field :likes_counter, value:0 %>
      <%= form.label :title,"Title", class:'label' %>
      <%= form.text_field :title, placeholder: 'Title of the post...', class:"title-input" %>
      <%= form.label :text, "Content", class:'label' %>
      <%= form.text_area :text, placeholder: 'Write your post...', class:"text-input" %>
      <%= form.submit "Submit Post", class:"submit-btn", id:"post-btn" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<section>
  <h2>Post Details</h2>
  <div class="post-container">
    <div class="post-header">
      <h3><%= @post.title%> By <%= @post.author.name%></h3>
      <span>Comments: <%= @post.comments_counter%>, Likes: <%= @post.likes_counter %></span>
    </div>
    <p><%= @post.text%></p>
     <%= form_with url: user_post_likes_path(@post.author, @post), method: :post do |form| %>
        <%= form.submit "Like", class:"submit-btn" %>
      <% end %>
  </div>
  <ul class="comments-list-container">
    <% if @post.comments_counter > 0%>
      <%@post.comments.each do |comment|%>
      <li><%= comment.author.name %> : <%= comment.text %></li>
      <%end%>
    <%else%>
      <li>No comment<li>
    <%end%>
     <%= form_with model: Comment, url: user_post_comments_path(@post.author, @post),class:'comment-form', method: :post do |form| %>
      <%= form.text_field :text, placeholder: 'Write your comment here...', class:"comment-text-cont" %>
      <%= form.submit "Add a comment", class:"submit-btn" %>
    <% end %>
  </ul>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <% if user_signed_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Posts", user_posts_path(current_user.id), class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Update Profile", edit_user_registration_path, class:"nav-link active" %>
          </li>
        </ul>
        <%= link_to "Sign Out", destroy_user_session_path, class:"btn btn-outline-danger",'data-turbo-method': :delete%>
      <% else %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link active" %>
          </li>
        </ul>
        <div class="gap-3">
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-outline-info" %>
          <%= link_to "Sign In", new_user_session_path, class:"btn btn-outline-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_post.html.erb
<div class="single-post">
  <a href="/users/<%=user.id%>/posts/<%=post.id%>">
  <h3><%= post.title %></h3>
  <p><%= post.text.first(150) %>...</p>
  <span>
    Comments: <%= post.comments_counter %>
    Likes: <%= post.likes_counter %>
  </span>
  </a>
<div>

app/views/shared/_user.html.erb
<div class="user-card-container">
  <img src="<%= user.photo %>" height="100" alt="<%= user.name + 'photo' %>" />
  <div class="username-and-posts">
    <h2><%= user.name %></h2>
    <h5>Number of posts: <%= user.post_counter %></h5>
  </div>
</div

app/views/users/index.html.erb
<section>
  <h2>List of Users</h2>
  <button type="button" class="btn btn-info">
    <%= link_to "Create A Post", new_post_path(current_user.id) , class: "new-post-link" %>
  </button>
  <div class="card mt-5">
    <div class="card-body">
      <ul class="users">
        <%@users.each do |user|%>
          <li class="users-list">
            <a href='/users/<%= user.id %>'>
              <%= render 'shared/user', user:user %>
            </a>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <h2>User Profile</h2>
  <%= render 'shared/user', user:@user %>
  <div class="bio-container">
    <h4>Bio</h4>
    <p>
      <%= @user.bio %>
    </p>
  </div>
  <ul class="posts-container">
  <% if @user.post_counter > 0 %>
    <% @user.last_three_posts.each do |post| %>
    <li>
      <%= render 'shared/post', {user: @user, post: post}%>
    </li>
    <%end%>
  <% else %>
    <li>No Posts</li>
  <% end %>
  </ul>
  <div class="all-posts-btn">
    <a href="/users/<%= @user.id %>/posts"><button type="button">See all posts</button></a>
  </div>
</section>